
export PYTHONSTARTUP=~/k3/misc/__start__.py

alias ls='ls -alh'

alias gacp="git add .;git commit -m 'gacp';git push origin master"

alias k3gacp="cd ~/k3;gacp;cd"

alias k3pull="cd ~/k3;git pull;cd"

git config --global credential.helper "cache --timeout=86400"

alias ipy="ipython --no-banner --no-confirm-exit"

export PYTHONPATH=~:$PYTHONPATH

export PATH=~/k3:$PATH
export PATH=~/k3/scripts:$PATH
export PATH=~/k3/scripts/gen:$PATH
export PATH=~/k3/scripts/net:$PATH
export PATH=~/k3/scripts/osx:$PATH
export PATH=~/k3/scripts/connect:$PATH
export PATH=~/k3/Menu:$PATH
export PATH=~/k3/utils/misc:$PATH

export COMPUTER_NAME=$HOSTNAME #'' #
PS1="\[\033[01;35m\]\w\[\033[00m\] $ "

export HISTSIZE=100000
export PYTHONUNBUFFERED=1 
# needed for time.sleep() to work properly

alias warn='python3 k3/scripts/osx/warn.py'
alias bkp='python3  k3/scripts/gen/bkp.py'
alias kgrep='python3 k3/scripts/gen/kgrep.py'
alias pygrep="top | awk '{print \$1,\$2,\$3,\$4,\$8}' | grep Python"
alias mclip='python3 k3/scripts/gen/mclip.py'
alias stowe='python3 k3/scripts/gen/stowe.py'
alias ke='python3 k3/scripts/gen/ke.py'
alias bk3='python3 k3/scripts/gen/bk3.py'
alias ky='python3 k3/scripts/gen/ky.py'
alias z='python3 k3/scripts/gen/zrun.py'

alias nav='python3 k3/utils/dict_/dict_nav.py'


alias sb="
	if [[ -d '/Volumes' ]]
	then
		echo 'sourcing bash_profile...'
		cd
		source ~/.bash_profile
	else
		echo 'sourcing bashrc...'
		cd
		source ~/.bashrc
	fi
"
# ln -s /Users/karlzipser/Library/Mobile\ Documents/com\~apple\~CloudDocs/iCloud-bucket/idata idata
#EOF
